version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - ELASTICSEARCH_NODE=https://5.75.227.63:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=rQQtbktwzFqAJS1h8YjP
      - ELASTICSEARCH_INDEX=imago
      - BASE_IMAGE_URL=https://www.imago-images.de
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  default:
    driver: bridge