name: Deploy Frontend to Amplify

on:
  push:
    branches: [ master, main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run tests
      working-directory: ./frontend
      run: npm test

    - name: Build application
      working-directory: ./frontend
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        NEXT_PUBLIC_APP_NAME: IMAGO Media Search

    - name: Deploy to AWS Amplify
      run: |
        # Create deployment package
        cd frontend
        zip -r ../frontend-build.zip .next/ public/ package.json next.config.ts
        cd ..
        
        # Upload to Amplify
        aws amplify start-deployment \
          --app-id ${{ env.AMPLIFY_APP_ID }} \
          --branch-name main \
          --source-url s3://amplify-builds-$(echo ${{ env.AMPLIFY_APP_ID }} | cut -c1-8)/frontend-build.zip
        
        # Wait for deployment to complete
        aws amplify list-jobs \
          --app-id ${{ env.AMPLIFY_APP_ID }} \
          --branch-name main \
          --max-results 1 \
          --query 'jobSummaries[0].status'